#define MAX_RESERVATION_SIZE 256
#define STATE_ACCESS_DELAY_US 500000  // 500ms
#define MAX_JOB_FILE_NAME_SIZE 256
#define MAX_SESSION_COUNT 10
#define SETUP_CLIENT 1
#define QUIT_CLIENT 2
#define CREATE_EVENT 3
#define RESERVE_SEATS 4
#define SHOW_EVENT 5
#define LIST_EVENTS 6